<script setup lang="ts">
const engine = defineModel<'DYNAMIC_AD_NETWORKS' | 'FIXED_ECPM'>('engine', { required: true })
const sharePercent = defineModel<number>('sharePercent', { required: true })

defineProps<{
  averageCpm: number
}>()
</script>

<template>
  <div class="rounded-xl border border-gray-800 bg-gray-900 p-6 shadow-sm space-y-6">
    <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-gray-800 pb-4">
      <div>
        <div class="flex items-center gap-2">
          <h2 class="text-lg font-bold text-white flex items-center gap-2">
            <UIcon name="i-heroicons-cpu-chip" class="h-6 w-6 text-primary-400" />
            Creator Monetization Engine Strategy
          </h2>
          <UBadge color="primary" variant="soft" size="xs" class="font-bold uppercase">Revenue Routing</UBadge>
        </div>
        <p class="mt-1 text-xs text-gray-400">
          Choose how creators earn income on your platform (Automatic Google AdSense & Adsterra API Revenue Share vs
          Fixed eCPM baseline).
        </p>
      </div>
    </div>

    <!-- Strategy Options (2 Cards) -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <!-- Option 1: Automated Google AdSense & Adsterra Revenue Share (RECOMMENDED) -->
      <div
        class="relative rounded-xl border-2 p-5 cursor-pointer transition-all duration-200"
        :class="
          engine === 'DYNAMIC_AD_NETWORKS'
            ? 'border-emerald-500 bg-gradient-to-br from-emerald-950/30 via-gray-900 to-gray-900 shadow-lg shadow-emerald-950/40'
            : 'border-gray-800 bg-gray-800/40 hover:border-gray-700'
        "
        @click="engine = 'DYNAMIC_AD_NETWORKS'"
      >
        <div class="flex items-start justify-between">
          <div class="flex items-center gap-3">
            <div class="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-500/20 text-emerald-400 font-bold">
              <UIcon name="i-heroicons-bolt" class="h-6 w-6" />
            </div>
            <div>
              <div class="flex items-center gap-2">
                <h3 class="text-base font-bold text-white">Auto AdSense & Adsterra Revenue Share</h3>
                <UBadge color="success" variant="solid" size="xs" class="font-bold">RECOMMENDED</UBadge>
              </div>
              <p class="text-xs text-emerald-400 font-medium mt-0.5">No manual $2.50 config required</p>
            </div>
          </div>
          <input
            type="radio"
            name="monetizationEngine"
            value="DYNAMIC_AD_NETWORKS"
            :checked="engine === 'DYNAMIC_AD_NETWORKS'"
            class="h-5 w-5 text-emerald-500 focus:ring-emerald-500 border-gray-700 bg-gray-800"
          />
        </div>

        <p class="mt-3 text-xs text-gray-300 leading-relaxed">
          Creators automatically earn revenue generated by Google AdSense & Adsterra Network ad impressions on their content
          based on live API yields (Avg CPM: ${{ averageCpm }}/1k views).
        </p>

        <div class="mt-4 pt-3 border-t border-gray-800/80 flex items-center justify-between text-[11px]">
          <span class="text-gray-400">Payout Model:</span>
          <span class="font-mono text-emerald-400 font-bold">Dynamic Revenue Share (API Live Sync)</span>
        </div>
      </div>

      <!-- Option 2: Fixed Baseline eCPM ($2.50 / 1k views) -->
      <div
        class="relative rounded-xl border-2 p-5 cursor-pointer transition-all duration-200"
        :class="
          engine === 'FIXED_ECPM'
            ? 'border-primary-500 bg-gradient-to-br from-primary-950/30 via-gray-900 to-gray-900 shadow-lg shadow-primary-950/40'
            : 'border-gray-800 bg-gray-800/40 hover:border-gray-700'
        "
        @click="engine = 'FIXED_ECPM'"
      >
        <div class="flex items-start justify-between">
          <div class="flex items-center gap-3">
            <div class="flex h-10 w-10 items-center justify-center rounded-xl bg-primary-500/20 text-primary-400 font-bold">
              <UIcon name="i-heroicons-banknotes" class="h-6 w-6" />
            </div>
            <div>
              <h3 class="text-base font-bold text-white">Fixed Baseline eCPM Rate</h3>
              <p class="text-xs text-gray-400 mt-0.5">Static $2.50 / 1,000 views rate model</p>
            </div>
          </div>
          <input
            type="radio"
            name="monetizationEngine"
            value="FIXED_ECPM"
            :checked="engine === 'FIXED_ECPM'"
            class="h-5 w-5 text-primary-500 focus:ring-primary-500 border-gray-700 bg-gray-800"
          />
        </div>

        <p class="mt-3 text-xs text-gray-300 leading-relaxed">
          Pays creators a fixed rate per 1,000 views (default $2.50/1k views), allowing manual per-creator custom rate overrides
          regardless of third-party ad yields.
        </p>

        <div class="mt-4 pt-3 border-t border-gray-800/80 flex items-center justify-between text-[11px]">
          <span class="text-gray-400">Payout Model:</span>
          <span class="font-mono text-amber-400 font-bold">Static eCPM Baseline</span>
        </div>
      </div>
    </div>

    <!-- Creator Revenue Share Percentage Setting (Applies when Auto Mode is selected) -->
    <div v-if="engine === 'DYNAMIC_AD_NETWORKS'" class="rounded-lg border border-emerald-500/30 bg-emerald-950/20 p-4 space-y-3">
      <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
        <div>
          <label class="text-xs font-bold text-white flex items-center gap-2">
            <UIcon name="i-heroicons-chart-pie" class="w-4 h-4 text-emerald-400" />
            Creator Ad Revenue Share Percentage
          </label>
          <p class="text-[11px] text-gray-400">
            Percentage of Google AdSense & Adsterra total ad earnings distributed to creators.
          </p>
        </div>
        <div class="flex items-center gap-2">
          <span class="text-lg font-extrabold text-emerald-400 font-mono">{{ sharePercent }}% Creator</span>
          <span class="text-xs text-gray-400">/ {{ 100 - sharePercent }}% Platform</span>
        </div>
      </div>

      <div class="flex items-center gap-4">
        <input
          v-model.number="sharePercent"
          type="range"
          min="50"
          max="95"
          step="5"
          class="w-full h-2 bg-gray-800 rounded-lg appearance-none cursor-pointer accent-emerald-500"
        />
      </div>
    </div>
  </div>
</template>
